[workarea]
include = ["src/*"]

[compile_commands]
search_paths = ["./build/compile_commands.json"]

[mutant_test]
build_cmd = ["./build.sh"]
test_cmd = ["./test.sh"]
# test_cmd_dir = ["./build/unittests"]
analyze_using_builtin = ["gtest"]
