name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install apt packages
      run: sudo apt-get install clang-15 ninja-build llvm-15-dev libclang-15-dev sqlite3 libsqlite3-dev dub z3
    - name: Install python packages
      run: pip install lit
    - name: Configure & generate
      run: ./configure.sh
    - name: Build
      run: ./build.sh
    - name: Test
      working-directory: ./build
      run: ninja check-verif
    - name: Self-Check
      working-directory: ./build
      run: for file in $(find ../src -name '*.cpp'); do echo $file; ./bin/verif-static-analyzer -p compile_commands.json $file -ignore-files="(/usr/lib/llvm-.*)|(.*/src/ESCA/.*)" | grep -vzq "warning:\ " || exit 1; done
    - name: Install dextools
      run: dub run dextool -- -h
    - name: Mutation test
      run: dub run dextool -- mutate analyze --fast-db-store && dub run dextool -- mutate test --max-runtime "5 minutes"
    - name: Mutation test result
      run: dub run dextool -- mutate report --section summary | tee /dev/tty | grep -P "Score:\s" | grep -Eo '[0-9]+(.[0-9]+)?' | tr -d '\n' | xargs -0 printf '%s >= 0.4\n' | bc | grep 1
